
# DIMENSÕES DA TELA
LARGURA = 480
ALTURA  = 600 

# TÍTULO DO JOGO
TITULO_JOGO = "Pacman"

# FPS
FPS = 30

# CORES
PRETO   = (0, 0, 0)
BRANCO  = (255, 255, 255)
AMARELO = (244, 233, 51)

# IMAGENS
SPRITESHEET        = "sprite_sheet.png"
PACKMAN_START_LOGO = "pacman-logo-1.png"

# FONTE
FONTE = "arial"

# AUDIOS
MUSICA_START = "intermission.wav"
TECLA_START  = "eat_dot_0.wav"

# PIXELS DA SPRITE
DIVISAO_GRANDE = 226.6

# TAMANHO SPRITE
PACMAN_TAMANHO_PIXEL = 14

# MOVIMENTOS DO PACMAN
NUMERO_MOVIMENTO_PACMAN_UP    = 3
NUMERO_MOVIMENTO_PACMAN_DOWN  = 3
NUMERO_MOVIMENTO_PACMAN_RIGHT = 3
NUMERO_MOVIMENTO_PACMAN_LEFT  = 3